components:
  schemas:
    CreateUser:
      properties:
        username:
          type: string
      required:
      - username
      type: object
    User:
      properties:
        id:
          type: integer
        username:
          type: string
      type: object
info:
  title: example-api
  version: '1.0'
openapi: 3.0.0
paths:
  /rest/users:
    description: userresource
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUser'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: SUCCESS
  /users:
    description: get_users
    get:
      parameters:
      - in: query
        name: username
        required: false
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/User'
                type: array
          description: SUCCESS
  /users/{user_id}:
    description: get_user_by_id
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: SUCCESS
    parameters:
    - in: path
      name: user_id
      required: true
      schema:
        type: integer
